---
# tasks file for ansible-role-proxmox/
- name: Ensure a locale exists
  locale_gen:
    name:   ru_RU.UTF-8
    state:  present
    
- name: Add Proxmox VE Key
  get_url:
    url:  http://download.proxmox.com/debian/proxmox-ve-release-5.x.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-ve-release-5.x.gpg

- name: Add Proxmox no-subscription repo
  apt_repository:
    repo:  deb http://download.proxmox.com/debian/pve stretch pve-no-subscription
    state: present
    
- name: Upgrade all packages
  apt:
    upgrade:       dist
    update_cache:  yes

- lineinfile:
    path: /etc/hosts
    regexp: '^192\.168\.88\.222'
    line: '192.168.88.222 stretch pvelocalhost'
    owner: root
    group: root
    mode: 0644

- lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 stretch.localdomain'
    owner: root
    group: root
    mode: 0644

- name: Configure postfix using debconf
  debconf:
    name: postfix
    question: postfix/main_mailer_type
    value: 'Internet Site'
    vtype: select

- name: Configure postfix using debconf
  debconf:
    name: postfix
    question: postfix/mailname
    value: 'stretch'
    vtype: select
    
- name: Install Proxmox VE packages
  apt:
    name:   "{{ item }}"
    state:  latest
  with_items:
    - proxmox-ve
    - postfix
    - open-iscsi